### ISSUE TITLE
Swift error: Failed to extract ServerMetadata from context

### ISSUE THREAD

**Issue by naivenut** [appscode/swift#51] opened 2017-10-16 14:02 UTC
Hello,

I installed swift in my k8s cluster which is running Tiller version 2.7.0-rc1. When I try to call it I get the following error:
```
curl 10.42.166.10:9855/tiller/v2/version/json`
{"code":4,"message":"context deadline exceeded"}
``` 
The pod logs show this:

```
1016 13:45:17.336235       7 server.go:89] [PROXYSERVER] Sarting Proxy Server at port [::]:9855
I1016 13:45:17.336282       7 server.go:168] Registering endpoint: RegisterReleaseServiceHandlerFromEndpoint
I1016 13:45:17.336327       7 server.go:120] Registering server: *release.Server
2017/10/16 13:46:10 Failed to extract ServerMetadata from context
2017/10/16 13:46:17 Failed to extract ServerMetadata from context
2017/10/16 13:46:29 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: operation was canceled"; Reconnecting to {tiller-deploy.kube-system:44134 <nil>}
```

So swift itself seems up and running, but the connection to tiller does not seem to work. The tiller endpoint (`tiller-deploy.kube-system:44134`) seems to be right.
What puzzles me though is the `Failed to extract ServerMetadata from context` part. Is this because I am running tiller 2.7.0-rc1 or is this not relevant?

FWIW, my local helm client runs just fine against tiller.

Thanks for reading,
-naivenut

**Comment by tamalsaha** [comment] 2017-10-16 17:27
@naivenut , what is the version of your Kubernetes cluster? I have tried Tiller version 2.7.0-rc1 with Swift 0.3.1 . It seems to work for me.

**Comment by tamalsaha** [comment] 2017-10-16 18:25
I have pushed [0.4.0-rc.0](https://github.com/appscode/swift/releases/tag/0.4.0-rc.0) for Helm 2.7.0-rc.1 . Please try that if you are still having issues.

**Comment by Nitrogenycs** [comment] 2017-10-16 19:24
Thanks for looking into this!

I've reproduced this on a different machine now which has the same setup. I am using swift 0.4.0-rc.0. Kubernetes version is 1.7.6. 
I have deployed Kubernetes via Rancher 2.0, see http://rancher.com/docs/rancher/v2.0/en/quick-start-guide/ . It's basically running a single docker container that will create a system identical to mine.
Is there anything else I can do, e.g. running with debug flags or something?

**Comment by Nitrogenycs** [comment] 2017-10-16 19:39
Hmm, might this be related to https://github.com/rancher/rancher/issues/10105 or what does ServerMetadata exactly do?

**Comment by tamalsaha** [comment] 2017-10-16 21:08
You can increase log level by setting `--v=` flag. https://github.com/appscode/swift/blob/27d961dc386eef482127338d8000b3439085fb50/hack/deploy/without-rbac.yaml#L17

Raise the log level to --v=8 temporarily and show us me the detailed error message. I am not familiar with Rancher and how it affects Tiller/Kubernetes.

**Comment by tamalsaha** [comment] 2017-10-30 01:35
Closing, since there is no user response. Please reopen if the issue persists.

**Closed by tamalsaha** 2017-10-30 01:35 UTC

**Comment by Nitrogenycs** [comment] 2017-11-13 09:04
Just for the record, I found the solution. It seemed like DNS was not working inside the container thus it could not resolve "tiller-deploy.kube-system" to its IP.

After I installed kube-dns in Rancher and re-installed swift things started to work. I suspect that the DNS resolution Rancher 2.0 alpha has out of the box at the moment does not really work (or I did not understand things properly). 

So thanks for creating Swift, it's cool to finally see the tiller json api :-)

**Comment by tamalsaha** [comment] 2017-11-13 09:20
@Nitrogenycs, glad that you identified the problem and fixed it! Thanks for letting us know.

**Comment by mumbley** [comment] 2019-02-12 14:08
I am having a similar problem (found this via a search on the pod log).  I can get it to work fine with a payload using curl but I am having problems when POSTing a payload via JS request.

Basically I *think* the problem is me manipulating the payload data submitted like so:
```
getReleaseConfig(releaseName, (data, err) => {
  if (err) {
    console.log(err);
  } else {

    let payload = {
        "chart_url": "<URL REDACTED>z",
        "namespace": newReleaseName,
        "values": {
          "raw": data
        }
      };
    console.log(JSON.stringify(payload));

    let postUrl = 'http://localhost:1337/tiller/v2/releases' + newReleaseName + '/json';
    request(
      {
        url: postUrl,
        form: JSON.stringify(payload),
        method: 'post'
      }, (err, httpResponse, body) => console.log(err, body));
    };
});
```

**Comment by mumbley** [comment] 2019-02-12 14:10
To be clear - I am extracting the deployment raw data via the swift API and then converting to a JSON object so I can extract the text for the particular deployment I want.  This is the callback for the request GET of the deployment (Hope that makes sense)
